version: '1.0'
services:
  - name: db
    type: mariadb
    version: 10.4
    configuration: StandAlone
    database: mautic
    username: mautic
    userPassword: null
    password: null
    ports:
      - 3306
    remoteAccess: false
    comments:
      userPassword: Password for user "mautic"
    deployTo:
      - mautic

  - name: mautic
    type: docker
    image: mautic/mautic
    version: fpm
    ports:
      - 9000
    remoteAccess: false
    env:
      MAUTIC_DB_HOST: "{{=service('db').getMasterAlias()}}"
      MAUTIC_DB_USER: "{{=service('db').get('username')}}"
      MAUTIC_DB_PASSWORD: "{{=service('db').get('userPassword')}}"
    deployTo:
      - mautic

  - name: pma
    type: docker
    image: phpmyadmin/phpmyadmin
    version: latest
    ports:
      - 80
    remoteAccess: false
    env:
      PMA_HOST: "{{=service('db').getMasterAlias()}}"
      PMA_PORT: "{{=service('db').getMainPort()}}"
    deployTo:
       - mautic

  - name: web
    type: nginx
    version: 1.17
    ports:
      - 80
      - 443
    remoteAccess: true
    serviceFiles:
      - name: mautic
        static: true
        src: ./configs/mautic.conf
      - name: pma
    deployTo:
      - mautic

hosts:
  - name: mautic
    requirements:
      cores: 1
      memory: 1
