version: '1.0'
services:
  - name: db
    type: mariadb
    version: 10.3
    configuration: StandAlone
    database: mautic
    username: mautic
    userPassword: null
    password: null
    ports:
      - 3306
    remoteAccess: false
    comments:
      userPassword: Password for user "mautic"
    deployTo:
      - mautic

  - name: mautic
    type: docker
    image: mautic/mautic
    version: fpm
    ports:
      - 9000
    remoteAccess: false
    env:
      MAUTIC_DB_HOST: "{{=service('db').getMasterAlias()}}"
      MAUTIC_DB_USER: "{{=service('db').get('username')}}"
      MAUTIC_DB_PASSWORD: "{{=service('db').get('userPassword')}}"
    deployTo:
      - mautic

  # - name: pma
  #   type: php
  #   version: 7.1
  #   source:
  #     type: git
  #     url: https://github.com/phpmyadmin/phpmyadmin
  #   extensions:
  #     - mysqli
  #     - opcache
  #   configFiles:
  #     - dest: $MAIN_PATH/config.inc.php
  #       src: ./configs/config.inc.php
  #   localDeps: composer install
  #   deployTo:
  #     - ghost

  - name: web
    type: nginx
    version: 1.15
    ports:
      - 80
      - 443
    remoteAccess: true
    serviceFiles:
      - name: mautic
        static: true
        src: ./configs/mautic.conf
    # - name: pma
    #   static: true
    deployTo:
      - mautic

hosts:
  - name: mautic
    requirements:
      cores: 1
      memory: 1
